name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      # Optional: debug that your secret exists (remove once green)
      - name: Debug token presence
        run: |
          echo "Token length:" $(printf %s "${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_TREE_02C17AB10 }}" | wc -c)

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GENTLE_TREE_02C17AB10 }}  # <-- your repo secret
          action: upload
          app_location: "."          # repo root is your static site
          api_location: ""           # no Functions API
          skip_app_build: true       # skip Oryx build (static files only)
          skip_api_build: true
