name: Azure Static Web Apps CI/CD (OIDC)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Get GitHub ID token
        id: oidc
        uses: actions/github-script@v7
        with:
          script: |
            const core = require('@actions/core');
            const id = await core.getIDToken();
            return id;
          result-encoding: string

      - name: Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: upload
          github_id_token: ${{ steps.oidc.outputs.result }}
          app_location: "."
          app_artifact_location: "."
          skip_app_build: true
          skip_api_build: true
